apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 950Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: mysql-operator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 850Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-operator
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql-operator
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Kagami2@"
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-root-pass
          #     key: password
        - name: MYSQL_DATABASE
          value: "site1_backend"
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-db-url
          #     key: database
        - name: MYSQL_USER
          value: "user1"
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-user-pass
          #     key: username
        - name: MYSQL_PASSWORD
          value: "Kagami2"@

          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-user-pass
          #     key: password
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
  namespace: mysql-operator
type: Opaque
data:
  password: S2FnYW1pMkA=

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
  namespace: mysql-operator
type: Opaque
data:
  username: dXNlcjE=
  password: S2FnYW1pMkA=

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
  namespace: mysql-operator
type: Opaque
data:
  database: c2l0ZTFfYmFja2VuZA==
